[package]
name = "rkvc"
version = "0.1.0"
edition = "2021"

[dependencies]
blake2 = { version = "0.10.6", default-features = false }
curve25519-dalek = { version = "4.1", default-features = false, features = ["zeroize", "precomputed-tables", "rand_core", "digest", "serde", "group"] }
digest = { version = "0.10.7", default-features = false }
ff = { version = "0.13.0", default-features = false, features = ["bits", "derive", "derive_bits"] }
group = { version = "0.13.0", default-features = false, features = ["rand"] }
lox-zkp = "0.8.1"
nimue = { version = "0.1.1", default-features = false, features = ["group"] }
rand_core = { version = "0.6.4", default-features = false }
zeroize = { version = "1.8.1", default-features = false }

[dev-dependencies]
itertools = "0.13.0"
